### PR TITLE
fix: reconnect to socket for all close codes except 1000

### LINKED ISSUE #575: After an error closes the websocket, a connection is not re-established
In the GraphQL Subscriptions interface a WebSocket is opened for subscription traffic. However, when the WebSocket closes due to an error, it will not be re-opened.

This may lead to lost update messages as there isn't any other mechanism to reopen the WebSocket.

### LINKED ISSUE #587: Multiple WebSockets are created when going offline and back online
When the Javascript API is included in browser code, multiple WebSockets are created every time the browser returns online.

This also compounds over time, we have seen cases where a browser client has 20+ WebSockets open simultaneously.

### PR DESCRIPTION
**Pull request by boxmein**
## Description of the change

This PR:

* Refactors graphql unit tests to make it possible to simulate socket closing
* Adds unit tests to cover multiple connection closing cases
* Changes GraphQL service to react to all non-1000 codes by reconnecting
* Implements truncated exponential backoff with jitter to control the reconnection rate
* Changes GraphQL service to disable ping-pong monitoring if a socket closes, removing errors when sending ping-messages to a closed or nonexisting socket
* Changes GraphQL service to avoid initializing a connection if it is currently being initialized
* Changes GraphQL service to close any pre-existing websocket and clean up

Todos:

- [x] Continue listening to `window "offline"` event 

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (Changed implementation, but existing functionality and APIs are not changed)

## Related issues

Fixes #575 
Fixes #587 

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [ ] Changes have been reviewed by at least one other engineer

### CODE REVIEW

File: src/lib/services/graphql/mock-set-interval.ts [hunk 1]
```diff
@@ -0,0 +1,57 @@
+/* global globalThis: false */
```
Comment (boxmein) [inline src/lib/services/graphql/mock-set-interval.ts:1]: `globalThis` is available in modern JS environments as an alias for the global object (window for the browser, global for Node...)

File: src/lib/services/graphql/graphql.service.ts [hunk 2]
```diff
@@ -419,7 +432,9 @@ export class GraphqlService {
   }
 
   private monitorWithOfflineEvent(): void {
-    window.addEventListener('offline', this.sendPingWithThisBound);
+    if (typeof window !== 'undefined') {
```
Comment (boxmein) [inline src/lib/services/graphql/graphql.service.ts:435]: In another location I use globalThis for working with node and browser, but here node will never emit an `"offline"` event on the global object so it's better to be explicit

File: src/lib/services/graphql/graphql.service.ts [hunk 3]
```diff
@@ -315,11 +320,16 @@ export class GraphqlService {
...
-      if (event.code === CLIENT_SIDE_CLOSE_EVENT) {
-        this.setConnectionStatus(ConnectionStatus.DISCONNECTED);
-        this.clearMonitoring();
-        this.socket = null;
-        return;
+
+      this.setConnectionStatus(ConnectionStatus.DISCONNECTED);
+      this.socket = null;
+
+      this.clearMonitoring();
```
Comment (boxmein) [inline src/lib/services/graphql/graphql.service.ts:327]: ⚠️ When a socket closes, the ping interval should be cancelled as well. Because it will retry connection anyway following the logic below.

HOWEVER, monitoring for window `"offline"` event will also be disabled, which is undesirable, because after the user returns online we should try to reconnect as soon as possible.

File: src/lib/util/randomized-exponential-backoff.ts [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+const MIN_BACKOFF_MS = 5000;
+const MIN_JITTER_MS = 300;
+const MAX_JITTER_MS = 1000;
+
+export function randomizedExponentialBackoff(
+  retryCount: number,
+): Promise<void> {
+  const timeOut = Math.min(
+    MAX_BACKOFF_MS,
+    Math.max(MIN_BACKOFF_MS, 2 ** retryCount * 1000),
```
Comment (boxmein) [inline src/lib/util/randomized-exponential-backoff.ts:11]: Reduce base to 1.2

**Comment by boxmein** [comment]
Duplicates socket

File: src/lib/util/randomized-exponential-backoff.ts [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+  );
+  const jitter = Math.floor(
+    Math.random() * (MAX_JITTER_MS - MIN_JITTER_MS) + MIN_JITTER_MS,
+  );
+  return new Promise((resolve) => setTimeout(resolve, timeOut + jitter));
```
Comment (boxmein) [inline src/lib/util/randomized-exponential-backoff.ts:16]: Figure out how to log the timeout.

Maybe it makes sense to split the function into 2 parts: calculating the timeout length, and a promise that resolves when a timeout completes? This way the consumer will get the timeout number as a variable.

File: src/lib/services/graphql/graphql-subscriptions-fixture.ts [hunk 6]
```diff
@@ -0,0 +1,117 @@
...
+    jest
+      .spyOn(this.graphqlService as any, 'fetchTemporaryApiKey')
+      .mockResolvedValue(keyValue);
+    jest
+      .spyOn(this.graphqlService as any, 'getServerUrl')
+      .mockReturnValue(SERVER_URL);
+  }
+
+  triggerSubscription(
+    query: DocumentNode | string = 'subscription { baba }',
```
Comment (KarlMae) [inline src/lib/services/graphql/graphql-subscriptions-fixture.ts:29]: I'm not sure how stringent we should be about tests - I think it's probably fine as is.

Though we have to be aware that when writing a new test that calls `triggerSubscription` and passes some new string, then `consumeSubscribeMessage` would not work.

Maybe `consumeSubscribeMessage` could also accept a query param with default value `subscription { baba }`, same as here.

File: src/lib/services/graphql/graphql-subscriptions.spec.ts [hunk 7]
```diff
@@ -0,0 +1,236 @@
...
+
+  beforeEach(async () => {
+    fixture = new GraphQLSubscriptionsFixture();
+  });
+
+  afterEach(async () => {
+    await fixture.cleanup();
+  });
+
+  it('sends connection init to start', async () => {
```
Comment (KarlMae) [inline src/lib/services/graphql/graphql-subscriptions.spec.ts:35]: Should we follow the naming convention of test names starting with "should"?

File: src/lib/services/graphql/graphql-subscriptions-jsdom-only.spec.ts [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+
+  beforeEach(async () => {
+    fixture = new GraphQLSubscriptionsFixture();
+  });
+
+  afterEach(async () => {
+    await fixture.cleanup();
+  });
+
+  it('when the browser returns online before a retry attempt, it will reconnect sooner', async () => {
```
Comment (KarlMae) [inline src/lib/services/graphql/graphql-subscriptions-jsdom-only.spec.ts:38]: Proposed rename after going through the code execution after not really getting what the test does

`should reconnect based on ping-pong before "onclose" retries connection`

**Review by KarlMae — CHANGES_REQUESTED** [review]
Testing as much as I knew how provided expected results ✅
Tons of tests that also cover weird code-paths ✅

Great work 🙌 

I added some small comments for clean-up :)

File: src/lib/services/graphql/graphql-subscriptions-fixture.ts [hunk 9]
```diff
@@ -0,0 +1,117 @@
+/* eslint-env jest */
+
+import { DocumentNode } from 'graphql';
```
[the remark this answers is not in the document]
Comment (boxmein) [reply src/lib/services/graphql/graphql-subscriptions-fixture.ts:3]: I'll use Jest conventional folder naming:

```
src/
+-lib/
  +- services/
    +- graphql/
      +- __tests__/
        +- graphql.service.spec.ts
        +- graphql-subscriptions.spec.ts
        +- graphql-subscriptions-jsdom-only.spec.ts
      +- __fixtures__/
        +- graphql-subscriptions-fixture.ts

File: src/lib/services/graphql/graphql-subscriptions.spec.ts (hunk 7 above)
Comment (boxmein) [reply src/lib/services/graphql/graphql-subscriptions.spec.ts]: This project has 6 tests with should prefix and 255 tests without should prefix

File: src/lib/services/graphql/graphql.service.ts [hunk 10]
```diff
@@ -315,11 +329,24 @@ export class GraphqlService {
...
+      if (event.code !== CLIENT_SIDE_CLOSE_EVENT) {
+        const timer = calculateRandomizedExponentialBackoffTime(
+          this.connectionAttemptsCount,
+        );
+        console.log(
+          `[Qminder API]: Waiting for ${timer.toFixed(
+            1,
+          )}ms before reconnecting`,
+        );
+        sleepMs(this.connectionAttemptsCount).then(() => {
```
Comment (2ndalpha) [inline src/lib/services/graphql/graphql.service.ts:346]: It should be `sleepMs(timer)`

File: src/lib/services/graphql/graphql.service.ts [hunk 11]
```diff
@@ -419,28 +447,34 @@ export class GraphqlService {
   }
 
   private monitorWithOfflineEvent(): void {
-    window.addEventListener('offline', this.sendPingWithThisBound);
+    if (typeof window !== 'undefined') {
+      window.removeEventListener('offline', this.sendPingWithThisBound);
```
Comment (2ndalpha) [inline src/lib/services/graphql/graphql.service.ts:451]: Why to remove and add again? To avoid adding listener twice?

File: src/lib/services/graphql/graphql.service.ts [hunk 12]
```diff
@@ -419,28 +447,34 @@ export class GraphqlService {
...
-    this.sendRawMessage(JSON.stringify({ type: MessageType.GQL_PING }));
+    if (this.socket) {
+      this.sendRawMessage(JSON.stringify({ type: MessageType.GQL_PING }));
+    }
   }
 
   private handleConnectionDrop(): void {
     console.warn(`[Qminder API]: Websocket connection dropped!`);
-
+    if (this.connectionStatus === ConnectionStatus.CONNECTING) {
```
Comment (2ndalpha) [inline src/lib/services/graphql/graphql.service.ts:468]: Shouldn't this check be before the `console.log`?

**Review by 2ndalpha — CHANGES_REQUESTED** [review]

File: src/lib/services/graphql/graphql.service.ts (hunk 11 above)
Comment (boxmein) [reply src/lib/services/graphql/graphql.service.ts:451]: Currently offline listener is added whenever websocket has opened, and never cleaned up. Would be good to avoid adding it multiple times

**Review by 2ndalpha — APPROVED** [review]
Good work! 👏
